# CMake generated Testfile for 
# Source directory: /git/uvcmetrics/test
# Build directory: /git/uvcmetrics/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(diags_test_01 "python" "/git/uvcmetrics/test/diagtest01.py" "/git/uvcmetrics/test/data" "--baseline=/git/uvcmetrics/test/baselines/")
add_test(diags_test_02 "python" "/git/uvcmetrics/test/diagtest02.py" "--datadir=/git/uvcmetrics/test/data" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_02 PROPERTIES  DEPENDS "diags_test_01")
add_test(diags_test_03 "python" "/git/uvcmetrics/test/diagtest03.py" "--datadir=/git/uvcmetrics/test/data" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_03 PROPERTIES  DEPENDS "diags_test_02")
add_test(diags_test_04 "python" "/git/uvcmetrics/test/diagtest04.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_04 PROPERTIES  DEPENDS "diags_test_03")
add_test(diags_test_4A "python" "/git/uvcmetrics/test/diagtest4A.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_4A PROPERTIES  DEPENDS "diags_test_04")
add_test(diags_test_05 "python" "/git/uvcmetrics/test/diagtest05.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_05 PROPERTIES  DEPENDS "diags_test_4A")
add_test(diags_test_06 "python" "/git/uvcmetrics/test/diagtest06.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_06 PROPERTIES  DEPENDS "diags_test_05")
add_test(diags_test_07 "python" "/git/uvcmetrics/test/diagtest07.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_07 PROPERTIES  DEPENDS "diags_test_06")
add_test(diags_test_08 "python" "/git/uvcmetrics/test/diagtest08.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_08 PROPERTIES  DEPENDS "diags_test_07")
add_test(diags_test_09 "python" "/git/uvcmetrics/test/diagtest09.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_09 PROPERTIES  DEPENDS "diags_test_08")
add_test(diags_test_10 "python" "/git/uvcmetrics/test/diagtest10.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_10 PROPERTIES  DEPENDS "diags_test_09")
add_test(diags_test_11 "python" "/git/uvcmetrics/test/diagtest11.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_11 PROPERTIES  DEPENDS "diags_test_10")
add_test(diags_test_12 "python" "/git/uvcmetrics/test/diagtest12.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_12 PROPERTIES  DEPENDS "diags_test_11")
add_test(diags_test_13 "python" "/git/uvcmetrics/test/diagtest13.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_13 PROPERTIES  DEPENDS "diags_test_12")
add_test(diags_test_15 "python" "/git/uvcmetrics/test/diagtest15.py" "--datadir=/git/uvcmetrics/test/data/" "--baseline=/git/uvcmetrics/test/baselines/")
set_tests_properties(diags_test_15 PROPERTIES  DEPENDS "diags_test_13")
