# collection 'regions' defaults to ['Global']
varlist = {}
collection = {}
obslist = {}
# *** Collection 11 ***
collection['11'] = {}
collection['11']['desc'] = 'Pacific annual cycle, Scatter plot plots'
collection['11']['preamble'] = ''
# *** Collection 10 ***
collection['10'] = {}
collection['10']['desc'] = 'Annual cycle line plots of global means'
collection['10']['preamble'] = ''
collection['10']['CLDMED'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['FSDS'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['FSNTOA'] = {'plottype': '10', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['10']['CLDLOW'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['LWCF'] = {'plottype': '10', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['10']['FSNTOAC'] = {'plottype': '10', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['10']['TS'] = {'plottype': '10', 'obs': ['NCEP_1']}
collection['10']['T_200'] = {'plottype': '10', 'obs': ['ECMWF_1', 'JRA25_1', 'AIRS_1', 'ERA40_1', 'NCEP_1']}
collection['10']['SWCF'] = {'plottype': '10', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['10']['ALBEDO'] = {'plottype': '10', 'obs': ['CERES2_1', 'CERES_1']}
collection['10']['CLDTOT'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['U_200'] = {'plottype': '10', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['10']['FLUTC'] = {'plottype': '10', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['10']['FSNS'] = {'plottype': '10', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['10']['Z3_500'] = {'plottype': '10', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['10']['RESTOA'] = {'plottype': '10', 'obs': ['ERBE_1']}
collection['10']['TGCLDLWP'] = {'plottype': '10', 'obs': ['SSMI_1', 'NVAP_1']}
collection['10']['FLUT'] = {'plottype': '10', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['10']['CLDTOT_VISIR'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['LHFLX'] = {'plottype': '10', 'obs': ['WHOI_1', 'ECMWF_1', 'ERA40_1']}
collection['10']['SHFLX'] = {'plottype': '10', 'obs': ['JRA25_1', 'NCEP_1', 'LARYEA_1']}
collection['10']['Z3_300'] = {'plottype': '10', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['10']['TREFHT'] = {'plottype': '10', 'obs': ['WILLMOTT_1', 'LEGATES_1', 'JRA25_1']}
collection['10']['FLDS'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['ALBEDOC'] = {'plottype': '10', 'obs': ['CERES2_1', 'CERES_1']}
collection['10']['ICEFRAC_SOUTH'] = {'plottype': '10', 'obs': ['SSMI_1', 'HADISST_1']}
collection['10']['CLDHGH_VISIR'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['EP'] = {'plottype': '10', 'obs': ['ECMWF_1', 'ERA40_1']}
collection['10']['CLDMED_VISIR'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['QFLX'] = {'plottype': '10', 'obs': ['WHOI_1', 'ECMWF_1', 'ERA40_1', 'LARYEA_1']}
collection['10']['PSL'] = {'plottype': '10', 'obs': ['JRA25_1', 'NCEP_1']}
collection['10']['T_850'] = {'plottype': '10', 'obs': ['ECMWF_1', 'JRA25_1', 'AIRS_1', 'ERA40_1', 'NCEP_1']}
collection['10']['SST'] = {'plottype': '10', 'obs': ['HADISST_1']}
collection['10']['FLNS'] = {'plottype': '10', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['10']['ICEFRAC_NORTH'] = {'plottype': '10', 'obs': ['SSMI_1', 'HADISST_1']}
collection['10']['CLDLOW_VISIR'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['PRECT'] = {'plottype': '10', 'obs': ['XA_1', 'GPCP_1', 'LEGATES_1', 'TRMM_1', 'SSMI_1']}
collection['10']['CLDHGH'] = {'plottype': '10', 'obs': ['ISCCP_1']}
collection['10']['PREH2O'] = {'plottype': '10', 'obs': ['NCEP_1', 'NVAP_1', 'JRA25_1', 'ERA40_1', 'ECMWF_1', 'SSMI_1']}
# *** Collection 13 ***
collection['13'] = {}
collection['13']['desc'] = 'ISCCP cloud simulator plots '
collection['13']['preamble'] = ''
# *** Collection 12 ***
collection['12'] = {}
collection['12']['desc'] = 'Vertical profile plots from 17 selected stations'
collection['12']['preamble'] = ''
# *** Collection 15 ***
collection['15'] = {}
collection['15']['desc'] = 'Annual Cycle at Select Stations plots'
collection['15']['preamble'] = ''
collection['15']['TMQ'] = {'plottype': '15', 'obs': ['NSA_1', 'TWP1_1', 'TWP2_1', 'SGP_1', 'TWP3_1']}
collection['15']['FSDS'] = {'plottype': '15', 'obs': ['SHEBA_1', 'TWP2_1', 'TWP1_1', 'SGP_1', 'TWP3_1', 'NSA_1']}
collection['15']['LHFLX'] = {'plottype': '15', 'obs': ['SGP_1']}
collection['15']['SHFLX'] = {'plottype': '15', 'obs': ['SGP_1']}
collection['15']['CLDTOT'] = {'plottype': '15', 'obs': ['TWP1_1', 'TWP3_1', 'SGP_1', 'TWP2_1', 'NSA_1']}
collection['15']['FLDS'] = {'plottype': '15', 'obs': ['SHEBA_1', 'TWP2_1', 'TWP1_1', 'SGP_1', 'TWP3_1', 'NSA_1']}
collection['15']['Q'] = {'plottype': '15', 'obs': ['NSA_1', 'TWP1_1', 'TWP2_1', 'SGP_1', 'TWP3_1']}
collection['15']['T'] = {'plottype': '15', 'obs': ['NSA_1', 'TWP2_1', 'TWP1_1', 'SGP_1', 'TWP3_1']}
collection['15']['MSE'] = {'plottype': '15', 'obs': ['NSA_1', 'TWP1_1', 'TWP2_1', 'SGP_1', 'TWP3_1']}
collection['15']['PRECT'] = {'plottype': '15', 'obs': ['SGP_1']}
collection['15']['TGCLDLWP'] = {'plottype': '15', 'obs': ['TWP1_1', 'TWP3_1', 'NSA_1', 'SGP_1', 'TWP2_1']}
collection['15']['CLOUD'] = {'plottype': '15', 'obs': ['NSA_1', 'TWP1_1', 'TWP2_1', 'SGP_1', 'TWP3_1']}
# *** Collection 14 ***
collection['14'] = {}
collection['14']['desc'] = 'Taylor Diagram plots '
collection['14']['preamble'] = '<p>Taylor Diagrams were developed by Karl Taylor at PCMDI (<a href="http://www.agu.org/pubs/crossref/2001/2000JD900719.shtml">paper</a>|<a href="http://www-pcmdi.llnl.gov/publications/pdf/55.pdf">tech note</a>) and aim to condense information about variance and RMSE characteristics of a particular model run when compared with observations in a single diagram. The tables summarize the individual metrics for each variable considered including: <ul><br> <li>bias, as absolute percentage difference from observations <li>variance, as a ratio of the observed variance <li>correlation, correlation coefficient with observations </ul><p>'
# *** Collection 3 ***
collection['3'] = {}
collection['3']['desc'] = 'Line plots of DJF, JJA and ANN zonal means'
collection['3']['preamble'] = ''
collection['3']['CLDMED'] = {'plottype': '3', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
collection['3']['FSDS'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['FSNTOA'] = {'plottype': '3', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['3']['CLDLOW'] = {'plottype': '3', 'obs': ['ISCCP_1', 'WARREN_1', 'CLOUDSAT_1']}
collection['3']['LWCF'] = {'plottype': '3', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['3']['FSNTOAC'] = {'plottype': '3', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['3']['TS'] = {'plottype': '3', 'obs': ['NCEP_1']}
collection['3']['SWCF'] = {'plottype': '3', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['3']['SWCFSRF'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['FLDSC'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['CLDTOT'] = {'plottype': '3', 'obs': ['ISCCP_1', 'WARREN_1']}
collection['3']['FLUTC'] = {'plottype': '3', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['3']['FSNS'] = {'plottype': '3', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['3']['TGCLDLWP'] = {'plottype': '3', 'obs': ['SSMI_1', 'NVAP_1', 'MODIS_1']}
collection['3']['FLUT'] = {'plottype': '3', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['3']['CLDTOT_VISIR'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['LHFLX'] = {'plottype': '3', 'obs': ['WHOI_1', 'ECMWF_1', 'JRA25_1', 'ERA40_1']}
collection['3']['SHFLX'] = {'plottype': '3', 'obs': ['JRA25_1', 'NCEP_1', 'LARYEA_1']}
collection['3']['TREFHT'] = {'plottype': '3', 'obs': ['WILLMOTT_1', 'LEGATES_1', 'JRA25_1', 'CRU_1']}
collection['3']['FLNSC'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['FLDS'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['FSDSC'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['LWCFSRF'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['FSNSC'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['CLDHGH_VISIR'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['PREH2O'] = {'plottype': '3', 'obs': ['NCEP_1', 'NVAP_1', 'JRA25_1', 'ERA40_1', 'MODIS_1', 'ECMWF_1', 'AIRS_1', 'SSMI_1']}
collection['3']['CLDMED_VISIR'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['QFLX'] = {'plottype': '3', 'obs': ['WHOI_1', 'ECMWF_1', 'LARYEA_1']}
collection['3']['PSL'] = {'plottype': '3', 'obs': ['JRA25_1', 'NCEP_1']}
collection['3']['FLNS'] = {'plottype': '3', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['3']['CLDLOW_VISIR'] = {'plottype': '3', 'obs': ['ISCCP_1']}
collection['3']['PRECT'] = {'plottype': '3', 'obs': ['XA_1', 'GPCP_1', 'LEGATES_1', 'TRMM_1', 'SSMI_1']}
collection['3']['CLDHGH'] = {'plottype': '3', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
# *** Collection 1 ***
collection['1'] = {}
collection['1']['desc'] = 'Tables of ANN, DJF, JJA, global and regional means and RMSE.'
collection['1']['preamble'] = ''
# *** Collection topten ***
collection['topten'] = {}
collection['topten']['desc'] = 'Tier 1A Diagnostics'
collection['topten']['preamble'] = ''
collection['topten']['PSL'] = {'seasons': ['ANN'], 'plottype': '5', 'obs': ['ERAI_1']}
collection['topten']['SURF_STRESS'] = {'seasons': ['ANN'], 'plottype': '6', 'obs': ['ERS_1']}
collection['topten']['TREFHT'] = {'seasons': ['ANN'], 'plottype': '5', 'obs': ['WILLMOTT_1']}
collection['topten']['LWCF'] = {'seasons': ['ANN'], 'plottype': '5', 'obs': ['CERES-EBAF_1']}
collection['topten']['PRECT'] = {'seasons': ['ANN'], 'plottype': '5', 'obs': ['GPCP_1']}
collection['topten']['AODVIS'] = {'seasons': ['ANN'], 'plottype': '5', 'obs': ['sat_1']}
collection['topten']['U'] = {'seasons': ['ANN'], 'plottype': '5', 'obs': ['ERAI_1']}
collection['topten']['T'] = {'seasons': ['ANN'], 'plottype': '4', 'obs': ['ERAI_1']}
collection['topten']['SWCF'] = {'seasons': ['ANN'], 'plottype': '5', 'obs': ['CERES-EBAF_1']}
collection['topten']['RELHUM'] = {'seasons': ['ANN'], 'plottype': '4', 'obs': ['ERAI_1']}
# *** Collection 2 ***
collection['2'] = {}
collection['2']['desc'] = 'Line plots of annual implied northward transports.'
collection['2']['preamble'] = '<p>The computation of the implied northward transports follows the conventions described in the paper by <a href="http://www.cgd.ucar.edu/cas/papers/jclim2001a/transpts.html">Trenberth and Caron (2001)</a>. Their corrections applied to the southern oceans poleward of 30S are not used in the calculations, and the NCEP derived values plotted here are their unadjusted values. Webpage about the NCEP derived data. A plot of the ocean basins used in the calculations.'
collection['2']['Atmospheric_heat'] = {'seasons': ['NA'], 'plottype': '2', 'obs': ['NA_1']}
collection['2']['Ocean_Freshwater'] = {'seasons': ['NA'], 'plottype': '2', 'obs': ['NA_1']}
collection['2']['Ocean_Heat'] = {'seasons': ['NA'], 'plottype': '2', 'obs': ['NA_1']}
# *** Collection 5 ***
collection['5'] = {}
collection['5']['desc'] = 'Horizontal contour plots of DJF, JJA and ANN means'
collection['5']['preamble'] = ''
collection['5']['CLDMED'] = {'plottype': '5', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
collection['5']['FSDS'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['FSNTOA'] = {'plottype': '5', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['5']['CLDLOW'] = {'plottype': '5', 'obs': ['ISCCP_1', 'WARREN_1', 'CLOUDSAT_1']}
collection['5']['LWCF'] = {'plottype': '5', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['5']['FSNTOAC'] = {'plottype': '5', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['5']['TS'] = {'plottype': '5', 'obs': ['NCEP_1']}
collection['5']['T_200'] = {'plottype': '5', 'obs': ['ECMWF_1', 'JRA25_1', 'AIRS_1', 'ERA40_1', 'NCEP_1']}
collection['5']['MEANTAU'] = {'plottype': '5', 'obs': ['ISCCP_1', 'MODIS_1']}
collection['5']['SWCF'] = {'plottype': '5', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['5']['SWCFSRF'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['ALBEDO'] = {'plottype': '5', 'obs': ['CERES2_1', 'CERES_1']}
collection['5']['SWCF_TROP'] = {'plottype': '5', 'obs': ['ERBE_TROP_1', 'CERES2_TROP_1', 'CERES_TROP_1']}
collection['5']['MEANTTOP'] = {'plottype': '5', 'obs': ['ISCCP_1', 'MODIS_1']}
collection['5']['PRECT_TROP'] = {'plottype': '5', 'obs': ['TRMM_TROP_1', 'LEGATES_TROP_1', 'XA_TROP_1', 'GPCP_TROP_1', 'SSMI_TROP_1']}
collection['5']['U_200'] = {'plottype': '5', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['5']['TTRP'] = {'plottype': '5', 'obs': ['ECMWF_1', 'NCEP_1']}
collection['5']['FLUTC'] = {'plottype': '5', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['5']['FLDSC'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['FSNS'] = {'plottype': '5', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['5']['Z3_500'] = {'plottype': '5', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['5']['TGCLDLWP'] = {'plottype': '5', 'obs': ['SSMI_TROP_1', 'NVAP_TROP_1', 'SSMI_1', 'NVAP_1', 'MODIS_1']}
collection['5']['FLUT'] = {'plottype': '5', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['5']['CLDTOT_VISIR'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['LHFLX'] = {'plottype': '5', 'obs': ['WHOI_1', 'ECMWF_1', 'JRA25_1', 'ERA40_1']}
collection['5']['SHFLX'] = {'plottype': '5', 'obs': ['JRA25_1', 'NCEP_1', 'LARYEA_1']}
collection['5']['Z3_300'] = {'plottype': '5', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['5']['TREFHT'] = {'plottype': '5', 'obs': ['WILLMOTT_1', 'LEGATES_1', 'JRA25_1', 'CRU_1']}
collection['5']['FLNSC'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['CLDTOT'] = {'plottype': '5', 'obs': ['ISCCP_1', 'WARREN_1', 'CLOUDSAT_1']}
collection['5']['FLDS'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['TCLDAREA'] = {'plottype': '5', 'obs': ['ISCCP_1', 'MODIS_1']}
collection['5']['ALBEDOC'] = {'plottype': '5', 'obs': ['CERES2_1', 'CERES_1']}
collection['5']['MEANPTOP'] = {'plottype': '5', 'obs': ['ISCCP_1', 'MODIS_1']}
collection['5']['LWCFSRF'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['FSNSC'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['CLDHGH_VISIR'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['EP'] = {'plottype': '5', 'obs': ['ECMWF_1']}
collection['5']['CLDMED_VISIR'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['QFLX'] = {'plottype': '5', 'obs': ['WHOI_1', 'ECMWF_1', 'LARYEA_1']}
collection['5']['PSL'] = {'plottype': '5', 'obs': ['JRA25_1', 'NCEP_1']}
collection['5']['T_850'] = {'plottype': '5', 'obs': ['ECMWF_1', 'JRA25_1', 'AIRS_1', 'ERA40_1', 'NCEP_1']}
collection['5']['SST'] = {'plottype': '5', 'obs': ['HADISST_PD_1', 'HADISST_PI_1', 'HADISST_1']}
collection['5']['FLNS'] = {'plottype': '5', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['5']['CLDLOW_VISIR'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['PRECT'] = {'plottype': '5', 'obs': ['XA_1', 'GPCP_1', 'LEGATES_1', 'SSMI_1']}
collection['5']['PRECT_LAND'] = {'plottype': '5', 'obs': ['PRECL_1']}
collection['5']['PRECIP'] = {'plottype': '5', 'obs': ['WILLMOTT_1']}
collection['5']['FSDSC'] = {'plottype': '5', 'obs': ['ISCCP_1']}
collection['5']['CLDHGH'] = {'plottype': '5', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
collection['5']['PREH2O'] = {'plottype': '5', 'obs': ['NCEP_1', 'NCEP_TROP_1', 'NVAP_1', 'NVAP_TROP_1', 'SSMI_TROP_1', 'ECMWF_TROP_1', 'ERA40_TROP_1', 'JRA25_1', 'ERA40_1', 'MODIS_1', 'MODIS_TROP_1', 'ECMWF_1', 'JRA25_TROP_1', 'SSMI_1']}
# *** Collection 4 ***
collection['4'] = {}
collection['4']['desc'] = 'Vertical contour plots of DJF, JJA and ANN zonal means'
collection['4']['preamble'] = ''
collection['4']['U'] = {'plottype': '4', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['4']['SHUM'] = {'plottype': '4', 'obs': ['ECMWF_1', 'JRA25_1', 'AIRS_1', 'ERA40_1', 'NCEP_1']}
collection['4']['RELHUM'] = {'plottype': '4', 'obs': ['ECMWF_1', 'NCEP_1', 'AIRS_1', 'ERA40_1']}
collection['4']['OMEGA'] = {'plottype': '4', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['4']['T'] = {'plottype': '4', 'obs': ['NCEP_1', 'JRA25_1', 'ERA40_1', 'ECMWF_1', 'AIRS_1']}
# *** Collection 7 ***
collection['7'] = {}
collection['7']['desc'] = 'Polar contour and vector plots of DJF, JJA and ANN means'
collection['7']['preamble'] = ''
collection['7']['PSL_SOUTH'] = {'plottype': '7', 'obs': ['JRA25_1', 'NCEP_1']}
collection['7']['CLDLOW_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'WARREN_1', 'CLOUDSAT_1']}
collection['7']['TREFHT_NORTH'] = {'plottype': '7', 'obs': ['WILLMOTT_1', 'CRU_1']}
collection['7']['Z3_500_SOUTH'] = {'plottype': '7', 'obs': ['ECMWF_1', 'JRA25_1', 'NCEP_1', 'ERA40_1']}
collection['7']['SHFLX_SOUTH'] = {'plottype': '7', 'obs': ['LARYEA_1']}
collection['7']['FSNS_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['7']['Z3_500_NORTH'] = {'plottype': '7', 'obs': ['ECMWF_1', 'JRA25_1', 'NCEP_1', 'ERA40_1']}
collection['7']['CLDTOT_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'WARREN_1', 'CLOUDSAT_1']}
collection['7']['FLUTC_SOUTH'] = {'plottype': '7', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['7']['CLDHGH_VISIR_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FLDSC_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['CLDHGH_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
collection['7']['PS_SOUTH'] = {'plottype': '7', 'obs': ['NCEP_1']}
collection['7']['FLNS_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['7']['FSDSC_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['PRECT_SOUTH'] = {'plottype': '7', 'obs': ['GPCP_1']}
collection['7']['FSDSC_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['ALBEDO_NORTH'] = {'plottype': '7', 'obs': ['CERES2_1', 'CERES_1']}
collection['7']['QFLX_SOUTH'] = {'plottype': '7', 'obs': ['LARYEA_1']}
collection['7']['FLDS_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FSNSC_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FSDS_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FLDS_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['SHFLX_NORTH'] = {'plottype': '7', 'obs': ['LARYEA_1']}
collection['7']['ALBEDO_SOUTH'] = {'plottype': '7', 'obs': ['CERES2_1', 'CERES_1']}
collection['7']['TS_NORTH'] = {'plottype': '7', 'obs': ['NCEP_1']}
collection['7']['FLNSC_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FLUT_NORTH'] = {'plottype': '7', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['7']['FSNS_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['7']['FSNTOAC_SOUTH'] = {'plottype': '7', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['7']['FSNTOA_NORTH'] = {'plottype': '7', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['7']['FLDSC_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['TREFHT_SOUTH'] = {'plottype': '7', 'obs': ['WILLMOTT_1']}
collection['7']['FLUTC_NORTH'] = {'plottype': '7', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['7']['ALBEDOC_SOUTH'] = {'plottype': '7', 'obs': ['CERES2_1', 'CERES_1']}
collection['7']['TS_SOUTH'] = {'plottype': '7', 'obs': ['NCEP_1']}
collection['7']['CLDHGH_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
collection['7']['CLDLOW_VISIR_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FSDS_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FSNSC_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['ALBEDOC_NORTH'] = {'plottype': '7', 'obs': ['CERES2_1', 'CERES_1']}
collection['7']['ICEFRAC_SOUTH'] = {'plottype': '7', 'obs': ['SSMI_1', 'HADISST_1']}
collection['7']['QFLX_NORTH'] = {'plottype': '7', 'obs': ['LARYEA_1']}
collection['7']['SURF_WIND_SOUTH'] = {'plottype': '7', 'obs': ['NCEP_1']}
collection['7']['CLDMED_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
collection['7']['PRECT_NORTH'] = {'plottype': '7', 'obs': ['GPCP_1']}
collection['7']['SURF_WIND_NORTH'] = {'plottype': '7', 'obs': ['NCEP_1']}
collection['7']['CLDMED_VISIR_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FLUT_SOUTH'] = {'plottype': '7', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['7']['PS_NORTH'] = {'plottype': '7', 'obs': ['NCEP_1']}
collection['7']['CLDTOT_VISIR_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['ICEFRAC_NORTH'] = {'plottype': '7', 'obs': ['SSMI_1', 'HADISST_1']}
collection['7']['FLNS_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'LARYEA_1']}
collection['7']['FLNSC_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1']}
collection['7']['FSNTOA_SOUTH'] = {'plottype': '7', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['7']['CLDTOT_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'WARREN_1', 'CLOUDSAT_1']}
collection['7']['PSL_NORTH'] = {'plottype': '7', 'obs': ['JRA25_1', 'NCEP_1']}
collection['7']['CLDLOW_NORTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'WARREN_1', 'CLOUDSAT_1']}
collection['7']['FSNTOAC_NORTH'] = {'plottype': '7', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['7']['CLDMED_SOUTH'] = {'plottype': '7', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
# *** Collection 6 ***
collection['6'] = {}
collection['6']['desc'] = 'Horizontal vector plots of DJF, JJA and ANN means'
collection['6']['preamble'] = ''
collection['6']['SURF_STRESS'] = {'plottype': '6', 'obs': ['NCEP_1', 'JRA25_1', 'LARYEA_1', 'ERS_1']}
collection['6']['SURF_STRESS_TROP'] = {'plottype': '6', 'obs': ['JRA25_TROP_1', 'ERS_TROP_1', 'NCEP_TROP_1', 'LARYEA_TROP_1']}
# *** Collection 9 ***
collection['9'] = {}
collection['9']['desc'] = 'Horizontal contour plots of DJF-JJA differences'
collection['9']['preamble'] = ''
collection['9']['CLDTOT'] = {'seasons': ['NA'], 'plottype': '9', 'obs': ['ISCCP_1', 'CLOUDSAT_1']}
collection['9']['PSL'] = {'seasons': ['NA'], 'plottype': '9', 'obs': ['NCEP_1']}
collection['9']['T_850'] = {'seasons': ['NA'], 'plottype': '9', 'obs': ['ECMWF_1', 'JRA25_1', 'AIRS_1', 'ERA40_1', 'NCEP_1']}
collection['9']['TREFHT'] = {'seasons': ['NA'], 'plottype': '9', 'obs': ['LEGATES_1', 'NCEP_1']}
collection['9']['LWCF'] = {'seasons': ['NA'], 'plottype': '9', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['9']['PRECT'] = {'seasons': ['NA'], 'plottype': '9', 'obs': ['XA_1', 'GPCP_1']}
collection['9']['SWCF'] = {'seasons': ['NA'], 'plottype': '9', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['9']['PREH2O'] = {'seasons': ['NA'], 'plottype': '9', 'obs': ['NCEP_1', 'NVAP_1', 'JRA25_1', 'ERA40_1', 'ECMWF_1']}
# *** Collection 8 ***
collection['8'] = {}
collection['8']['desc'] = 'Annual cycle contour plots of zonal means'
collection['8']['preamble'] = ''
collection['8']['PREH2O'] = {'plottype': '8', 'obs': ['NCEP_1', 'NVAP_1', 'JRA25_1', 'ERA40_1', 'ECMWF_1']}
collection['8']['PRECT'] = {'plottype': '8', 'obs': ['XA_1', 'GPCP_1']}
collection['8']['FLUT'] = {'plottype': '8', 'obs': ['ERBE_1', 'CERES2_1', 'CERES_1']}
collection['8']['U_200'] = {'plottype': '8', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
# *** Collection 4a ***
collection['4a'] = {}
collection['4a']['desc'] = 'Vertical (XZ) contour plots of DJF, JJA and ANN meridional means'
collection['4a']['preamble'] = ''
collection['4a']['U'] = {'plottype': '4a', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['4a']['SHUM'] = {'plottype': '4a', 'obs': ['ECMWF_1', 'JRA25_1', 'AIRS_1', 'ERA40_1', 'NCEP_1']}
collection['4a']['RELHUM'] = {'plottype': '4a', 'obs': ['ECMWF_1', 'NCEP_1', 'AIRS_1', 'ERA40_1']}
collection['4a']['OMEGA'] = {'plottype': '4a', 'obs': ['ECMWF_1', 'NCEP_1', 'JRA25_1', 'ERA40_1']}
collection['4a']['T'] = {'plottype': '4a', 'obs': ['NCEP_1', 'JRA25_1', 'ERA40_1', 'ECMWF_1', 'AIRS_1']}
# *** Variables List ***
varlist['PSL_SOUTH'] = {'desc': 'Sea-level pressure (Southern)'}
varlist['TREFHT_NORTH'] = {'desc': '2-meter temperature (land) (Northern)'}
varlist['SHFLX_SOUTH'] = {'desc': 'Surface sensible heat flux (Southern)'}
varlist['FSNTOAC'] = {'desc': 'TOA clearsky new SW flux'}
varlist['QFLX_SOUTH'] = {'desc': 'Surface water flux (Southern)'}
varlist['CLDHGH_NORTH'] = {'desc': 'High cloud amount (IR clouds) (Northern)'}
varlist['FSNTOA_SOUTH'] = {'desc': 'TOA net SW flux (Southern)'}
varlist['TTRP'] = {'desc': 'Tropopause temperature'}
varlist['Z3_500_NORTH'] = {'desc': '500 mb geopotential height (Northern)'}
varlist['FSNS'] = {'desc': 'Surf Net SW flux'}
varlist['FLDS_SOUTH'] = {'desc': 'Surf LW downwelling flux (Southern)'}
varlist['CLDLOW_NORTH'] = {'desc': 'Low cloud amount (IR clouds) (Northern)'}
varlist['ALBEDOC_SOUTH'] = {'desc': 'TOA clearsky albedo (Southern)'}
varlist['TS_NORTH'] = {'desc': 'Surface temperature (Northern)'}
varlist['TCLDAREA'] = {'desc': 'Total cloud area (Day)'}
varlist['T'] = {'desc': 'Temperature'}
varlist['PRECT_NORTH'] = {'desc': 'Precipitation rate (Northern)'}
varlist['FLNSC_SOUTH'] = {'desc': 'Clearsky Surf Net LW flux (Southern)'}
varlist['PS_NORTH'] = {'desc': 'Surface pressure (Northern)'}
varlist['PREH2O'] = {'desc': 'Total precipitable water'}
varlist['CLDMED'] = {'desc': 'Mid cloud amount (IR clouds)'}
varlist['FSDS'] = {'desc': 'Surf SW downwelling flux'}
varlist['FSNTOA'] = {'desc': 'TOA new SW flux'}
varlist['CLDLOW'] = {'desc': 'Low cloud amount (IR clouds)'}
varlist['FLDSC_NORTH'] = {'desc': 'Clearsky Surf LW downwelling flux (Northern)'}
varlist['FSNTOA_NORTH'] = {'desc': 'TOA net SW flux (Northern)'}
varlist['CLDMED_VISIR_NORTH'] = {'desc': 'Mid cloud amount (VIS/IR/NIR) clouds) (Northern)'}
varlist['MEANTAU'] = {'desc': 'Mean cloud optical thickness (Day)'}
varlist['SWCF'] = {'desc': 'TOA shortwave cloud forcing'}
varlist['ALBEDO'] = {'desc': 'TOA Albedo'}
varlist['SWCF_TROP'] = {'desc': 'TOA shortwave cloud forcing'}
varlist['Z3_300'] = {'desc': '300 mb geopotential height'}
varlist['MEANTTOP'] = {'desc': 'Mean cloud top temperature (Day)'}
varlist['PRECT_TROP'] = {'desc': 'Tropical Precipitation rate'}
varlist['FSDSC_SOUTH'] = {'desc': 'Clearsky Surf SW downwelling flux (Southern)'}
varlist['FLDS_NORTH'] = {'desc': 'Surf LW downwelling flux (Northern)'}
varlist['FSNSC_NORTH'] = {'desc': 'Clearsky Surf Net SW flux (Northern)'}
varlist['FSDS_SOUTH'] = {'desc': 'Surf SW downwelling flux (Southern)'}
varlist['RESTOA'] = {'desc': 'TOA residual energy flux'}
varlist['SHFLX_NORTH'] = {'desc': 'Surface sensible heat flux (Northern)'}
varlist['SHFLX'] = {'desc': 'Surface sensible heat flux'}
varlist['PS_SOUTH'] = {'desc': 'Surface pressure (Southern)'}
varlist['FLNSC'] = {'desc': 'Clearsky Surf Net LW Flux'}
varlist['CLDHGH_SOUTH'] = {'desc': 'High cloud amount (IR clouds) (Southern)'}
varlist['FSNSC_SOUTH'] = {'desc': 'Clearsky Surf Net SW flux (Southern)'}
varlist['ALBEDOC_NORTH'] = {'desc': 'TOA clearsky albedo (Northern)'}
varlist['ALBEDOC'] = {'desc': 'TOA clearsky albedo'}
varlist['ICEFRAC_SOUTH'] = {'desc': 'Sea-ice area (Southern)'}
varlist['RELHUM'] = {'desc': 'Relative humidity'}
varlist['EP'] = {'desc': 'Evaporation - precipitation'}
varlist['QFLX'] = {'desc': 'Surface water flux'}
varlist['PSL'] = {'desc': 'Sea-level pressure'}
varlist['CLDTOT_VISIR_NORTH'] = {'desc': 'Total cloud amount (VIS/IR/NIR) clouds) (Northern)'}
varlist['SST'] = {'desc': 'Sea surface temperature'}
varlist['FLNS'] = {'desc': 'Surf Net LW flux'}
varlist['ICEFRAC_NORTH'] = {'desc': 'Sea-ice area (Northern)'}
varlist['CLDLOW_VISIR'] = {'desc': 'Low cloud amount (VIS/IR/NIR clouds)'}
varlist['PRECT'] = {'desc': 'Precipitation rate'}
varlist['PRECT_LAND'] = {'desc': 'Precipitation rate (land)'}
varlist['PRECIP'] = {'desc': 'Cumulative precipitation (land)'}
varlist['TMQ'] = {'desc': 'Precipitable Water'}
varlist['LWCF'] = {'desc': 'TOA longwave cloud forcing'}
varlist['FLDS'] = {'desc': 'Surf LW downwelling flux'}
varlist['T_200'] = {'desc': '200 mb temperature'}
varlist['Z3_500_SOUTH'] = {'desc': '500 mb geopotential height (Southern)'}
varlist['SWCFSRF'] = {'desc': 'Surf SW Cloud Forcing'}
varlist['SURF_STRESS_TROP'] = {'desc': 'Surface wind stress (ocean)'}
varlist['CLDLOW_SOUTH'] = {'desc': 'Low cloud amount (IR clouds) (Southern)'}
varlist['TS_SOUTH'] = {'desc': 'Surface temperature (Southern)'}
varlist['Z3_500'] = {'desc': '500 mb geopotential height'}
varlist['OMEGA'] = {'desc': 'Pressure vertical velocity'}
varlist['FLUT'] = {'desc': 'TOA upward LW flux'}
varlist['FLUT_NORTH'] = {'desc': 'TOA upward LW flux (Northern)'}
varlist['TREFHT_SOUTH'] = {'desc': '2-meter temperature (land) (Southern)'}
varlist['TREFHT'] = {'desc': '2-meter air temperature (land)'}
varlist['CLDLOW_VISIR_NORTH'] = {'desc': 'Low cloud amount (VIS/IR/NIR) clouds) (Northern)'}
varlist['Atmospheric_heat'] = {'desc': 'Atmospheric Heat', 'filekey':'ATM_HEAT'}
varlist['FSDSC'] = {'desc': 'Clearsky Surf SW downwelling flux'}
varlist['QFLX_NORTH'] = {'desc': 'Surface water flux (Northern)'}
varlist['SURF_WIND_SOUTH'] = {'desc': 'Near surface wind (Southern)'}
varlist['CLDHGH_VISIR'] = {'desc': 'High cloud amount (VIS/IR/NIR clouds)'}
varlist['FLNS_SOUTH'] = {'desc': 'Surf Net LW flux (Southern)'}
varlist['FLUT_SOUTH'] = {'desc': 'TOA upward LW flux (Southern)'}
varlist['SURF_STRESS'] = {'desc': 'Surface wind stress (ocean)'}
varlist['FLDSC'] = {'desc': 'Clearsky Surf LW downwelling flux'}
varlist['CLDTOT_SOUTH'] = {'desc': 'Total cloud amount (IR clouds) (Southern)'}
varlist['CLDHGH'] = {'desc': 'High cloud amount (IR clouds)'}
varlist['FSNS_NORTH'] = {'desc': 'Surf Net SW flux (Northern)'}
varlist['FLUTC'] = {'desc': 'TOA clearsky upward LW flux'}
varlist['Ocean_Freshwater'] = {'desc': 'Ocean Freshwater', 'filekey':'OCN_FRESH'}
varlist['CLDTOT_NORTH'] = {'desc': 'Total cloud amount (IR clouds) (Northern)'}
varlist['FLUTC_SOUTH'] = {'desc': 'TOA clearsky upward LW flux (Southern)'}
varlist['MSE'] = {'desc': 'Moist Static Energy'}
varlist['SHUM'] = {'desc': 'Specific humidity'}
varlist['FLNS_NORTH'] = {'desc': 'Surf Net LW flux (Northern)'}
varlist['FSDSC_NORTH'] = {'desc': 'Clearsky Surf SW downwelling flux (Northern)'}
varlist['U_200'] = {'desc': '200 mb zonal wind'}
varlist['ALBEDO_NORTH'] = {'desc': 'TOA albedo (Northern)'}
varlist['TS'] = {'desc': 'Surface temperature'}
varlist['ALBEDO_SOUTH'] = {'desc': 'TOA albedo (Southern)'}
varlist['TGCLDLWP'] = {'desc': 'Cloud liquid water'}
varlist['CLOUD'] = {'desc': 'Cloud Fraction'}
varlist['FSNS_SOUTH'] = {'desc': 'Surf Net SW flux (Southern)'}
varlist['FSNTOAC_SOUTH'] = {'desc': 'TOA clearsky net SW flux (Southern)'}
varlist['CLDTOT_VISIR'] = {'desc': 'Total cloud amount (VIS/IR/NIR clouds)'}
varlist['LHFLX'] = {'desc': 'Surface latent heat flux'}
varlist['FLDSC_SOUTH'] = {'desc': 'Clearsky Surf LW downwelling flux (Southern)'}
varlist['FLUTC_NORTH'] = {'desc': 'TOA clearsky upward LW flux (Northern)'}
varlist['CLDTOT'] = {'desc': 'Mid cloud amount (IR clouds)'}
varlist['CLDMED_NORTH'] = {'desc': 'Mid cloud amount (IR clouds) (Northern)'}
varlist['Q'] = {'desc': 'Specific Humidity'}
varlist['FSDS_NORTH'] = {'desc': 'Surf SW downwelling flux (Northern)'}
varlist['U'] = {'desc': 'Zonal Wind'}
varlist['Ocean_Heat'] = {'desc': 'Ocean Heat', 'filekey':'OCN_HEAT'}
varlist['LWCFSRF'] = {'desc': 'Surf LW Cloud Forcing'}
varlist['FSNSC'] = {'desc': 'Clearsky Surf Net SW Flux'}
varlist['SURF_WIND_NORTH'] = {'desc': 'Near surface wind (Northern)'}
varlist['CLDMED_VISIR'] = {'desc': 'Mid cloud amount (VIS/IR/NIR clouds)'}
varlist['MEANPTOP'] = {'desc': 'Mean cloud top pressure (Day)'}
varlist['T_850'] = {'desc': '850 mb temperature'}
varlist['PRECT_SOUTH'] = {'desc': 'Precipitation rate (Southern)'}
varlist['CLDHGH_VISIR_NORTH'] = {'desc': 'High cloud amount (VIS/IR/NIR) clouds) (Northern)'}
varlist['FLNSC_NORTH'] = {'desc': 'Clearsky Surf Net LW flux (Northern)'}
varlist['PSL_NORTH'] = {'desc': 'Sea-level pressure (Northern)'}
varlist['AODVIS'] = {'desc': 'Aerosol optical depth'}
varlist['FSNTOAC_NORTH'] = {'desc': 'TOA clearsky net SW flux (Northern)'}
varlist['CLDMED_SOUTH'] = {'desc': 'Mid cloud amount (IR clouds) (Southern)'}
# *** Observation sets ***
obslist['MODIS_TROP_1'] = {'filekey': 'MODIS_TROP', 'desc': 'MODIS Mar2000-Aug2004 - Tropics'}
obslist['HADISST_PD_1'] = {'filekey': 'HADISST_PD', 'desc': 'HadISST/OI.v2 (Present Day) 1999-2008'}
obslist['WARREN_1'] = {'filekey': 'WARREN', 'desc': 'Warren Cloud Surface OBS'}
obslist['LEGATES_1'] = {'filekey': 'LEGATES', 'desc': 'Legates and Willmott 1920-80'}
obslist['SSMI_TROP_1'] = {'filekey': 'SSMI_TROP', 'desc': 'SSM/I (Wentz) 1987-2000 - Tropics'}
obslist['SGP_1'] = {'filekey': 'SGP', 'desc': 'Southern Great Plains (SGP)'}
obslist['ERA40_1'] = {'filekey': 'ERA40', 'desc': 'ERA40 Reanalysis 1980-2001'}
obslist['ERS_1'] = {'filekey': 'ERS', 'desc': 'ERS Scatterometer 1992-2000'}
obslist['CLOUDSAT_1'] = {'filekey': 'CLOUDSAT', 'desc': 'CLOUDSAT (Radar+Lidar) Sep2006-Nov2008'}
obslist['WHOI_1'] = {'filekey': 'WHOI', 'desc': 'Woods Hole OAFLUX 1958-2006'}
obslist['NCEP_1'] = {'filekey': 'NCEP', 'desc': 'NCEP Reanalysis 1979-98'}
obslist['AOD_550_1'] = {'filekey': 'AOD_550', 'desc': 'AOD Data'}
obslist['NSA_1'] = {'filekey': 'NSA', 'desc': 'North Slope of Alaska (NSA)'}
obslist['LEGATES_TROP_1'] = {'filekey': 'LEGATES_TROP', 'desc': 'Legates and Willmott 1920-80 - Tropics'}
obslist['JRA25_1'] = {'filekey': 'JRA25', 'desc': 'JRA25 Reanalysis 1979-04'}
obslist['TWP2_1'] = {'filekey': 'TWP2', 'desc': 'Tropical Western Pacific--Region 2 (TWP2)'}
obslist['ERBE_1'] = {'filekey': 'ERBE', 'desc': 'ERBE Feb1985-Apr1989'}
obslist['CERES_1'] = {'filekey': 'CERES', 'desc': 'CERES 2000-2003'}
obslist['JRA25_TROP_1'] = {'filekey': 'JRA25_TROP', 'desc': 'JRA25 Reanalysis 1979-04 - Tropics'}
obslist['WILLMOTT_1'] = {'filekey': 'WILLMOTT', 'desc': 'Willmott and Matsuura 1950-99'}
obslist['PRECL_1'] = {'filekey': 'PRECL', 'desc': 'PREC/L (CMAP) 1948-2001'}
obslist['TWP3_1'] = {'filekey': 'TWP3', 'desc': 'Tropical Western Pacific--Region 3 (TWP3)'}
obslist['ERBE_TROP_1'] = {'filekey': 'ERBE_TROP', 'desc': 'ERBE Feb1985-Apr1989 - Tropics'}
obslist['NVAP_TROP_1'] = {'filekey': 'NVAP_TROP', 'desc': 'NVAP 1988-1999 - Tropics'}
obslist['ERA40_TROP_1'] = {'filekey': 'ERA40_TROP', 'desc': 'ERA40 Reanalysis 1980-2001 - Tropics'}
obslist['TWP1_1'] = {'filekey': 'TWP1', 'desc': 'Tropical Western Pacific--Region 1 (TWP1)'}
obslist['ECMWF_TROP_1'] = {'filekey': 'ECMWF_TROP', 'desc': 'ECMWF Reanalysis 1979-93 - Tropics'}
obslist['GPCP_1'] = {'filekey': 'GPCP', 'desc': 'GPCP 1979-2003'}
obslist['CERES2_1'] = {'filekey': 'CERES2', 'desc': 'CERES2 March 2000-October 2005'}
obslist['CRU_1'] = {'filekey': 'CRU', 'desc': 'IPCC/CRU Climatology 1961-90'}
obslist['NCEP_TROP_1'] = {'filekey': 'NCEP_TROP', 'desc': 'NCEP Reanalysis 1979-98 - Tropics'}
obslist['XA_TROP_1'] = {'filekey': 'XA_TROP', 'desc': 'CMAP (Xie-Arkin) 1979-98 - Tropics'}
obslist['GPCP_TROP_1'] = {'filekey': 'GPCP_TROP', 'desc': 'GPCP 1979-2003 - Tropics'}
obslist['ERAI_1'] = {'filekey': 'ERAI', 'desc': 'ERA Interim Reanalysis'}
obslist['HADISST_PI_1'] = {'filekey': 'HADISST_PI', 'desc': 'HadISST/OI.v2 (Pre-Indust) 1870-1900'}
obslist['TRMM_TROP_1'] = {'filekey': 'TRMM_TROP', 'desc': 'TRMM (3B43) 1998-Feb2004 - Tropics'}
obslist['CERES-EBAF_1'] = {'filekey': 'CERES-EBAF', 'desc': 'CERES-EBAF'}
obslist['AIRS_1'] = {'filekey': 'AIRS', 'desc': 'AIRS IR Sounder 2002-06'}
obslist['LARYEA_TROP_1'] = {'filekey': 'LARYEA_TROP', 'desc': 'Large-Yeager 1984-2004 - Tropics'}
obslist['NVAP_1'] = {'filekey': 'NVAP', 'desc': 'NVAP 1988-1999'}
obslist['SHEBA_1'] = {'filekey': 'SHEBA', 'desc': 'Surface Heat Budget of the Arctic Ocean (SHEBA)'}
obslist['ERS_TROP_1'] = {'filekey': 'ERS_TROP', 'desc': 'ERS Scatterometer 1992-2000 - Tropics'}
obslist['LARYEA_1'] = {'filekey': 'LARYEA', 'desc': 'Large-Yeager 1984-2004'}
obslist['N/A_1'] = {'filekey': 'N/A', 'desc': 'NA'}
obslist['CERES2_TROP_1'] = {'filekey': 'CERES2_TROP', 'desc': 'CERES2 March 2000-October 2005 - Tropics'}
obslist['CERES_TROP_1'] = {'filekey': 'CERES_TROP', 'desc': 'CERES 2000-2003 - Tropics'}
obslist['MODIS_1'] = {'filekey': 'MODIS', 'desc': 'MODIS Mar2000-Aug2004'}
obslist['ISCCP_1'] = {'filekey': 'ISCCP', 'desc': 'ISCCP D1 Daytime Jul1983-Sep2001'}
obslist['TRMM_1'] = {'filekey': 'TRMM', 'desc': 'TRMM (3B43) 1998-Feb2004'}
obslist['HADISST_1'] = {'filekey': 'HADISST', 'desc': 'HadISST/OI.v2 (Climatology) 1982-2001'}
obslist['XA_1'] = {'filekey': 'XA', 'desc': 'CMAP (Xie-Arkin) 1979-98'}
obslist['SSMI_1'] = {'filekey': 'SSMI', 'desc': 'SSM/I (Wentz) 1987-2000'}
obslist['ECMWF_1'] = {'filekey': 'ECMWF', 'desc': 'ECMWF Reanalysis 1979-93'}
