package_name = "lmwg"
package_raelm = "land"

package_ids = ['set1', 'set2', 'set3', 'set4', 'set5', 'set6', 'set7', 'set8', 'set9']
#eventually, we should do more with the other keys, but for now most of the code will just key off set names
package_sets ={
   'set1': {'id': 'set1', 
    'name': 'Line Plots of Annual Trends in Energy Balance, Soil water/ice temperature, runoff, snow water/ice, photosynthesis', 
    'type': 'line', 
    'climatology': ['annual'], 
    'status':'active'},
   'set2': {'id':'set2',
    'name': 'Horizontal contour plots of DJF, MAM, JJA, SON, and ANN means', 
    'type':'contour',
    'climatology': ['seasonal', 'annual'], 
    'status':'active'},
   'set3': {'id':'set3',
    'name': 'Line plots of monthly climatology: regional air temperature, precipitation, runoff, snow depth, radiative fluxes, and turbulent fluxes', 
    'type':'line', 
    'climatologies':['monthly'], 
    'status':'active'},
   'set4': {'id':'set4',
    'name':'Vertical Profiles at selected land raobs stations',
    'type':None,
    'climatologies':[],
    'status':'inactive'},
   'set5': {'id':'set5',
    'name':'Tables of annual means',
    'type':'table',
    'climatologies':['annual'],
    'status':'active'},
   'set6': {'id':'set6',
    'name':'Line plotso f annual trends in regional soil water/ice and temperature, runoff, snow, water/ice, photosynthesis',
    'type':'regionalline',
    'climatologies':['annual'],
    'status':'active'},
   'set7': {'id':'set7',
    'name':'Line plots, tables, and maps of RTM river flow and discharge to oceans',
    'type':['line','table','maps'],
    'climatologies':['annual'],
    'status':'active'},
   'set8': {'id':'set8',
    'name':'Line and contour plots of Ocean/Land.Atmosphere CO2 Exchange',
    'type':['line','countour'],
    'climatologies':None,
    'status':'inactive'},
   'set9': {'id':'set9',
    'name':'Contour plots and statistics for precipitation and temperature. Statistics include DJF, JJA, and ANN biases and RMSE, correlation and standard deviation of the annual cycle relative to observations',
    'type':'contour',
    'climatologies':['annual', 'seasonal'],
    'status':'inactive'}}
