NAME = subtitle
TM = vcanvas2.createtemplate(NAME, tm2)
TM.script(NAME+'_raobs')

NAME = 'JAN'
NAME = 'APR'
NAME = 'JUL'
NAME = 'OCT'

NAME = 'global_means'

NAME = 'GLOBAL_HEAT_TRANSPORT'
NAME = 'PACIFIC_HEAT_TRANSPORT'
NAME = 'ATLANTIC_HEAT_TRANSPORT'
NAME = 'INDIAN_HEAT_TRANSPORT'


In makeplots, variable Ocean_Heat running time for making plots: 18.9504988194
In makeplots, variable Ocean_Heat running time for writing png files: 0.908640146255
Makeplots, variable Ocean_Heat total time is 789.176780939
(2.8) bash-3.2$ ls
ATLANTIC_HEAT_TRANSPORT_2_x_0.json	GLOBAL_HEAT_TRANSPORT_0_x_0.json	INDIAN_HEAT_TRANSPORT_3_x_0.json	PACIFIC_HEAT_TRANSPORT_1_x_0.json	make_plot_set_2_json.py
ATLANTIC_HEAT_TRANSPORT_2_x_1.json	GLOBAL_HEAT_TRANSPORT_0_x_1.json	INDIAN_HEAT_TRANSPORT_3_x_1.json	PACIFIC_HEAT_TRANSPORT_1_x_1.json
(2.8) bash-3.2$ rm make_plot_set_2_json.py
(2.8) bash-3.2$ ls
ATLANTIC_HEAT_TRANSPORT_2_x_0.json	GLOBAL_HEAT_TRANSPORT_0_x_0.json	INDIAN_HEAT_TRANSPORT_3_x_0.json	PACIFIC_HEAT_TRANSPORT_1_x_0.json
ATLANTIC_HEAT_TRANSPORT_2_x_1.json	GLOBAL_HEAT_TRANSPORT_0_x_1.json	INDIAN_HEAT_TRANSPORT_3_x_1.json	PACIFIC_HEAT_TRANSPORT_1_x_1.json
(2.8) bash-3.2$ mv ATLANTIC_HEAT_TRANSPORT_2_x_0.json ATLANTIC_HEAT_TRANSPORT_0.json
(2.8) bash-3.2$ mv ATLANTIC_HEAT_TRANSPORT_2_x_1.json ATLANTIC_HEAT_TRANSPORT_1.json
(2.8) bash-3.2$ mv GLOBAL_HEAT_TRANSPORT_0_x_0.json GLOBAL_HEAT_TRANSPORT_0.json
(2.8) bash-3.2$ mv GLOBAL_HEAT_TRANSPORT_0_x_1.json GLOBAL_HEAT_TRANSPORT_1.json
(2.8) bash-3.2$ mv INDIAN_HEAT_TRANSPORT_3_x_0.json INDIAN_HEAT_TRANSPORT_0.json
(2.8) bash-3.2$ mv INDIAN_HEAT_TRANSPORT_3_x_1.json INDIAN_HEAT_TRANSPORT_1.json
(2.8) bash-3.2$ mv PACIFIC_HEAT_TRANSPORT_1_x_0.json PACIFIC_HEAT_TRANSPORT_0.json
(2.8) bash-3.2$ mv PACIFIC_HEAT_TRANSPORT_1_x_1.json PACIFIC_HEAT_TRANSPORT_1.json
(2.8) bash-3.2$ ls
ATLANTIC_HEAT_TRANSPORT_0.json	GLOBAL_HEAT_TRANSPORT_0.json	INDIAN_HEAT_TRANSPORT_0.json	PACIFIC_HEAT_TRANSPORT_0.json	trans.py
ATLANTIC_HEAT_TRANSPORT_1.json	GLOBAL_HEAT_TRANSPORT_1.json	INDIAN_HEAT_TRANSPORT_1.json	PACIFIC_HEAT_TRANSPORT_1.json
